### ISSUE TITLE
Set ClientID automatically

### ISSUE THREAD

**Issue by baibaratsky** [baibaratsky/yii2-ga-measurement-protocol#1]

**Comment by terales** [comment]
Do you want to set it from cookie?
Should we extract `1592987322.1509026938` from `_ga` cookie's value `GA1.2.1592987322.1509026938`?

If yes I would like to implement it

**Comment by baibaratsky** [comment]
Hi! Yep, I think it could be a good option.

**Comment by terales** [comment]
Thanks for a reply! I would submit PR this weekend, as this is a same thing I want to implement in our project.
