### ISSUE TITLE
Version v2.0.0 released

### ISSUE THREAD

**Issue by jorgeborges** [baibaratsky/yii2-ga-measurement-protocol#2]
Just a heads up. I merged your PR and released v2.0.0 of the php-ga-measurement-protocol package. As you surely know, it uses Guzzle 6 as the HTTP client so it no longer supports PHP 5.4, only 5.5 or above.

I'll maintain a separate branch v1 for version 1 releases, only important fixes will be applied to version 1 branch.

Feel free to do something similar so that users of your package can start using Guzzle 6.

Thanks for contributing!

**Comment by baibaratsky** [comment]
Thanks! Just [updated](https://github.com/baibaratsky/yii2-ga-measurement-protocol/releases/tag/v1.1.0) my package.
