### ISSUE TITLE
Upgrade package to support PHP 7.2

### ISSUE THREAD

**Issue by terales** [baibaratsky/yii2-ga-measurement-protocol#4]
There is an `Object` class used here which is [forbidden in PHP 7.2](https://wiki.php.net/rfc/object-typehint):
https://github.com/baibaratsky/yii2-ga-measurement-protocol/blob/9ee151c3eaf3bf9fb87dc28fff10e10bc87ec549/MeasurementProtocol.php#L6

[Yii2 has a special upgrading instructions](https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2012):
> For extensions that have classes extending from `yii\base\Object`, to be compatible with PHP 7.2, you need to require `"yiisoft/yii2": "~2.0.13"` in composer.json and change affected classes to extend from `yii\base\BaseObject` instead. It is not possible to allow Yii versions <2.0.13 and be compatible with PHP 7.2 or higher.

I suggest:

* in `1.*` version set dependency on PHP environments: `"php": "<7.2"`
* create `2.0.0` version with different Yii2 dependency: `"yiisoft/yii2": ">=2.0.13"`

In that way, we ensure that people would be able to use wrapper in all possible scenarios if basic `theiconic/php-ga-measurement-protocol` package works, of course

Do you see another solution?
If not then can I prepare PRs for suggested one?

**Comment by baibaratsky** [comment]
Yep, your solution is fine.
